### ISSUE TITLE
support for html angular

### ISSUE THREAD

**Issue by ElCapitanSponge** [liuderchi/ide-html#13]
No support for HTML(angular) templates

**Comment by liuderchi** [comment]
@cpt-agemman thanks for the suggestion. 

The *Register Additional Grammar (Experimental)* section in the package setting provides a solution.

Please do the following
  1. open your template then do command `Editor: Log Cursor Scope`
  2. copy the first list item in the notification dialog: *Scopes at Cursor*
  3. open package setting pane of `ide-html`
  4. paste the copied grammar at the input of *Register Additional Grammar (Experimental)*
  5. restart Atom

BTW what's the grammar of your angular templates? I am considering including it to default setting.

**Comment by ElCapitanSponge** [comment]
Closing as I use VS Code, and Atom has been flagged as EOL.
