### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MortalCatalyst** [liuderchi/ide-html#25]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by liuderchi** [comment]
@MortalCatalyst Is there anything we can help?

**Comment by liuderchi** [comment]
Will close this issue since this issue seems inactive
