### ISSUE TITLE
No outline available 

### ISSUE THREAD

**Issue by tarikkavaz** [liuderchi/ide-html#31]
## Description

I'm receiving an error message: 
### No outline available
This is likely an error with the language package.

![screen shot 2018-05-16 at 09 44 19](https://user-images.githubusercontent.com/5513457/40100896-4ce57a72-58ee-11e8-84a2-b91be4d194e6.png)
 

* Atom 1.27.0
* ide-html 0.4.2

**Comment by liuderchi** [comment]
@tarikkavaz Thanks for report.
Would [FAQ no.2](https://github.com/liuderchi/ide-html#faq) solve this issue?
