### ISSUE TITLE
html renderer

### ISSUE THREAD

**Issue by rgarrigue** [liuderchi/ide-html#43]
## Description

This is a feature request.

I'ld like to be able to display an html page in atom, found nothing so far, I expected this package to do the trick. Nothing complicated, I've all inclusive tests reports, it's a waste of tome to have to open it somewhere else.

**Comment by liuderchi** [comment]
Can this package https://github.com/harmsk/atom-html-preview satisfy your request?

**Comment by rgarrigue** [comment]
I switched to vscode since then.
